### ISSUE TITLE
Ajouter des pads existants (add existing pads)

### ISSUE THREAD

**Issue by numahell** [zamentur/libreto#1]
Tout d'abord, super appli, très jolie et qui répond à pas mal de besoins !

Pouvoir ajouter des pads déjà existants, par exemple quand dans le pad de menu l'item commence par http, ne pas ajouter le chemin proposé

*Add existing pads, for exemple when in menu pad, the item starts with 'http', don't add the path*

**Comment by Ventricule** [comment]
Oui, bonne idée, merci de ta suggestion.
Ça reste simple et permet une transition en douceur pour des utilisateurs ayant leurs pads déjà créés.

Je pense l'ajouter avec une esthétique à la [Kirbytext](https://getkirby.com/docs/content/text), par exemple : 
`Titre du pad (url: http://framapad.org/pad)`
Qui permettrai d'ajouter d'autres options dans le futur, par exemple:
`Titre du pad (url: http://framapad.org/pad color: red)`

_Good idea, thank for suggesting !
It doesnt make things more complicated for basic usage but it add the capability for users to embbed easily there pads._

**Comment by Ventricule** [comment]
Hello,

J'ai réécris l'appli avec des objets. Pas mal de boulot, mais c'est moins le bazar. 
Je suis assez preneur de retours sur le code d'ailleurs.

On peut maintenant donner des options aux pads (url, color et visibility). @numahell, tu me diras si ça marche et si ça te sert.

J'ai aussi intégré la super librairie [bindery.js](https://github.com/evnbr/bindery) qui permet d'exporter les pads sous forme d'un petit livret bien mis en page.

Autre nouveauté : on peut changer d'instance etherpad. Il suffit d'écrire son nom comme sous-domaine, par exemple framapad.libreto.net ou board.libreto.net. 

J'ai hésité à changer l'instance par défaut pour board.net. En effet, avec Framapad, le chargement du pad est souvent bloqué. Ça se débloque lorsque on passe en navigation privé sans cache ni cookies. Si quelqu'un sait d'où ça peut venir je suis preneur !

_Hello
The code has been rewrited with objects. That's more clear and modular now.
You can customize pads with tags, for exemple `pad (color: red url: https://framapad.org/p/mypad)` return a pad with a specific url.
You can change the pad instance by writing its name as subdomain (actualy only framapad and board), `e.g.: board.libreto.net/mypad`._
