### ISSUE TITLE
Exporter / Télécharger

### ISSUE THREAD

**Issue by Drakone** [zamentur/libreto#6]
![](https://forum.arn-fai.net/uploads/default/optimized/1X/dba31ae8e06424b4ad01f92cd8579c09ea6d8590_2_690x392.gif)

**Comment by Ventricule** [comment]
C'est réparé, 
L'export buguait à cause du fichier book.js absent (options de mise en page du livre)
Le téléchargement buguait à cause d'un vieux code oublié
